# Generated by Django 5.2.16 on 2026-07-13 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseIMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_delivery_date', models.DateField()),
                ('warehouse', models.CharField(max_length=100)),
                ('grn_status', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=50, unique=True)),
                ('buyer_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('wood_type', models.CharField(max_length=50)),
                ('finish_color', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='samples/')),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('contractor', 'Contractor')], default='contractor', max_length=20)),
                ('batch_category', models.CharField(blank=True, choices=[('sanding', 'Sanding'), ('polish', 'Polish'), ('fitting', 'Fitting'), ('packaging', 'Packaging')], help_text='Required for Supervisors — defines which manufacturing stage they manage', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor this contractor reports to', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractors', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=50)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='erp.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SandingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanding_batches', to='erp.sample')),
                ('supervisor', models.ForeignKey(limit_choices_to={'batch_category': 'sanding', 'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sanding_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('supervisor', 'sample')},
            },
        ),
        migrations.CreateModel(
            name='SandingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contractor_notes', models.TextField(blank=True, help_text='Notes added by contractor on completion')),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sanding_assignments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='erp.sandingbatch')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SandingQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('reject', 'Reject')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc', to='erp.sandingassignment')),
                ('checked_by', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sanding_qc_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
