# Generated by Django 5.2.16 on 2026-07-15 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='image',
        ),
        migrations.AddField(
            model_name='sample',
            name='box_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Breadth (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Height (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='box_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Length (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight (kg)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight (kg)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='po',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PO'),
        ),
        migrations.AddField(
            model_name='sample',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Breadth (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Height (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Length (cm)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='style_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Style No.'),
        ),
        migrations.AddField(
            model_name='sample',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='sample',
            name='total_cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Total CBM'),
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='samples/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='erp.sample')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
