# Generated by Django 5.2.16 on 2026-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_sample_image_sample_box_breadth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='finish_color',
            field=models.CharField(max_length=150),
        ),
    ]
