# Generated by Django 5.2.16 on 2026-07-16 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_sample_finish_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='box_breadth',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='box_height',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='box_length',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='cbm',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='po',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='total_cbm',
        ),
        migrations.CreateModel(
            name='BuyerMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_no', models.CharField(max_length=100)),
                ('buyer_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('wood_type', models.CharField(max_length=50)),
                ('finish_color', models.CharField(max_length=150)),
                ('size_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Length (cm)')),
                ('size_breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Breadth (cm)')),
                ('size_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Height (cm)')),
                ('remark', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_masters', to='erp.buyer')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_masters', to='erp.sample')),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po', models.CharField(blank=True, max_length=100, null=True, verbose_name='PO')),
                ('cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)')),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Total CBM')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Amount')),
                ('box_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Length (cm)')),
                ('box_breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Breadth (cm)')),
                ('box_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Height (cm)')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight (kg)')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight (kg)')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='erp.buyer')),
                ('buyer_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='erp.buyermaster')),
            ],
        ),
    ]
