# Generated by Django 5.2.16 on 2026-07-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_buyer_remove_sample_box_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='po',
            name='units',
            field=models.IntegerField(blank=True, null=True, verbose_name='Units'),
        ),
    ]
