# Generated by Django 5.2.16 on 2026-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Production', 'Production'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed')], default='Confirmed', max_length=50, verbose_name='Status'),
        ),
    ]
