# Generated by Django 5.2.16 on 2026-07-18 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_po_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='buyer_code',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='wood_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='erp.buyer', verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM'),
        ),
        migrations.AddField(
            model_name='sample',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_breadth_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Breadth (in)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_height_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Height (in)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='size_length_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Length (in)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Name'),
        ),
    ]
