# Generated by Django 5.2.16 on 2026-07-20 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_remove_sample_buyer_code_remove_sample_wood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pi_no', models.CharField(max_length=100, unique=True, verbose_name='PI No.')),
                ('pi_date', models.DateField(blank=True, null=True, verbose_name='PI Date')),
                ('buyer_order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name="Buyer's Order No.")),
                ('buyer_order_date', models.DateField(blank=True, null=True, verbose_name="Buyer's Order Date")),
                ('exporter_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name="Exporter's Ref.")),
                ('other_references', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Reference(s)')),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyer Name')),
                ('buyer_other_consignee', models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyer (if other than consignee)')),
                ('department_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department #')),
                ('pre_carriage_by', models.CharField(blank=True, default='Trailer', max_length=100, null=True, verbose_name='Pre-Carriage by')),
                ('place_of_receipt', models.CharField(blank=True, default='Jaipur', max_length=100, null=True, verbose_name='Place of Receipt by Pre-carrier')),
                ('vessel_flight_no', models.CharField(blank=True, default='By Sea', max_length=100, null=True, verbose_name='Vessel / Flight No.')),
                ('port_of_loading', models.CharField(blank=True, default='Mundra', max_length=100, null=True, verbose_name='Port of Loading')),
                ('port_of_discharge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Port of Discharge')),
                ('place_of_delivery', models.CharField(blank=True, default='UNITED KINGDOM', max_length=100, null=True, verbose_name='Place of Delivery')),
                ('country_of_origin', models.CharField(blank=True, default='INDIA', max_length=100, null=True, verbose_name='Country of Origin')),
                ('country_final_destination', models.CharField(blank=True, default='UK', max_length=100, null=True, verbose_name='Country of Final Destination')),
                ('terms_payment', models.CharField(blank=True, default='Payment: T/T', max_length=200, null=True, verbose_name='Terms of Payment')),
                ('terms_delivery', models.CharField(blank=True, default='Delivery: 30-July-26 Ex-Factory', max_length=200, null=True, verbose_name='Terms of Delivery')),
                ('category_header', models.CharField(blank=True, default='Wooden Furniture Items', max_length=200, null=True, verbose_name='Category Header')),
                ('declaration_text', models.TextField(blank=True, default='We declare that this invoice shows that the actual price of the goods and that all particulars are true and correct. We are not registered under Central Excise Act 1944 and Rules made there under and no cenvat credit or input stage benefits in any input has been availed by us or supporting manufacturer. No duty free input either imported or procured locally has been used in the export product. The value declared is fair and same is equivalent to PMV of the goods. The goods are non antique and not art treasure. We further declare that neither red sandors wood nor any oher prohibited wood has been used in the manufacturing of above items.', null=True, verbose_name='Declaration Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performa_invoices', to='erp.buyer', verbose_name='Buyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformaInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_no', models.CharField(max_length=100, verbose_name='Style No.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of Goods')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image URL / Path')),
                ('dimension_w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (cm)')),
                ('dimension_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth (cm)')),
                ('dimension_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height (cm)')),
                ('volume_per_pc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Per Pc')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('total_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Total Volume')),
                ('rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rate US$')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount US$')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.performainvoice')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_items', to='erp.po')),
            ],
        ),
    ]
