# Generated by Django 5.2.16 on 2026-07-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_performainvoice_performainvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='performainvoice',
            name='delivered_to',
            field=models.TextField(blank=True, null=True, verbose_name='Delivered To'),
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='ex_factory_date',
            field=models.CharField(blank=True, default='19 April, 2026', max_length=100, null=True, verbose_name='Ex-Factory Date'),
        ),
        migrations.AddField(
            model_name='performainvoice',
            name='payment_terms',
            field=models.CharField(blank=True, default='100% TT 30 Days from BL', max_length=200, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='buyer_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_items', to='erp.buyermaster'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='buyer_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer #'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='finish',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='po',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='erp.performainvoice', verbose_name='PI Reference'),
        ),
        migrations.AddField(
            model_name='po',
            name='pi_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='erp.performainvoiceitem', verbose_name='PI Item Reference'),
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='buyer_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Buyer's Order No. / PO #"),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of Goods / Name'),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Quantity / Units'),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='volume_per_pc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Per Pc (CBM)'),
        ),
        migrations.AlterField(
            model_name='po',
            name='buyer_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='erp.buyermaster'),
        ),
    ]
