# Generated by Django 5.2.16 on 2026-07-20 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_performainvoice_delivered_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performainvoice',
            name='delivered_to',
        ),
        migrations.RemoveField(
            model_name='performainvoice',
            name='ex_factory_date',
        ),
        migrations.RemoveField(
            model_name='performainvoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='buyer_master',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='buyer_no',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='po',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='po',
            name='pi_item',
        ),
        migrations.AlterField(
            model_name='performainvoice',
            name='buyer_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Buyer's Order No."),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of Goods'),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='performainvoiceitem',
            name='volume_per_pc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Volume Per Pc'),
        ),
        migrations.AlterField(
            model_name='po',
            name='buyer_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='erp.buyermaster'),
        ),
        migrations.CreateModel(
            name='BuyerPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pi_no', models.CharField(max_length=100, unique=True, verbose_name='PI / PO Ref No.')),
                ('pi_date', models.DateField(blank=True, null=True, verbose_name='PI Date')),
                ('ex_factory_date', models.DateField(blank=True, null=True, verbose_name='Ex-Factory Date')),
                ('payment_terms', models.CharField(blank=True, default='100% TT 30 Days from BL', max_length=200, null=True, verbose_name='Payment Terms')),
                ('delivered_to_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivered To Contact Name')),
                ('delivered_to_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Delivered To Company Name')),
                ('delivered_to_address', models.TextField(blank=True, null=True, verbose_name='Delivered To Address')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_pis', to='erp.buyer', verbose_name='Buyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='po',
            name='buyer_pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='erp.buyerpi', verbose_name='Performa Invoice'),
        ),
        migrations.CreateModel(
            name='BuyerPIItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('buyer_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer #')),
                ('style_no', models.CharField(max_length=100, verbose_name='Style No.')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Name')),
                ('size_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Length (cm)')),
                ('size_breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Breadth (cm)')),
                ('size_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size Height (cm)')),
                ('material', models.CharField(blank=True, max_length=150, null=True, verbose_name='Material')),
                ('finish_color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Finish')),
                ('cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Total CBM')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Amount')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('buyer_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_items', to='erp.buyermaster')),
                ('buyer_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.buyerpi')),
            ],
        ),
    ]
