# Generated by Django 5.2.16 on 2026-07-21 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_performainvoice_delivered_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('gstin', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSTIN/UIN')),
                ('state_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='State Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='performainvoiceitem',
            name='po',
        ),
        migrations.AddField(
            model_name='performainvoiceitem',
            name='po_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Legacy PO Ref'),
        ),
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=100, unique=True, verbose_name='PO Number')),
                ('po_date', models.DateField(verbose_name='PO Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='PO Due Date')),
                ('mode_of_payment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mode of Payment')),
                ('terms_of_delivery', models.TextField(blank=True, null=True, verbose_name='Terms of Delivery')),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor')),
                ('nku_refs', models.CharField(blank=True, max_length=300, null=True, verbose_name='NKU Reference Numbers')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPOItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description of Goods')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit (pcs/mtr/Ft²)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rate (INR)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount (INR)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_po_items', to='erp.buyer', verbose_name='Buyer (Order Reference)')),
                ('buyer_pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_po_items', to='erp.buyerpi', verbose_name='Buyer PI Reference')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.supplierpo', verbose_name='Supplier PO')),
            ],
        ),
        migrations.DeleteModel(
            name='PO',
        ),
    ]
