# Generated by Django 5.2.16 on 2026-07-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_supplier_remove_performainvoiceitem_po_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseIMO',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
