# Generated by Django 5.2.16 on 2026-07-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_delete_purchaseimo_delete_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPOItemDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of defective pieces', max_digits=10)),
                ('defective_image', models.ImageField(upload_to='po_defects/')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='erp.supplierpoitem')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
