# Generated by Django 5.2.16 on 2026-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_supplierpoitemdefect'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpoitem',
            name='passed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Passed Quantity'),
        ),
    ]
