# Generated by Django 5.2.16 on 2026-07-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_supplierpoitemdefect_admin_reply_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpoitemdefect',
            name='defective_image',
            field=models.ImageField(blank=True, null=True, upload_to='po_defects/'),
        ),
        migrations.CreateModel(
            name='SupplierPOItemDefectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='po_defects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='erp.supplierpoitemdefect')),
            ],
        ),
    ]
