# Generated by Django 5.2.16 on 2026-07-21 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_supplierpoitemdefect_defective_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermaster',
            name='box_size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Box Size'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='costing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costing'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='packaging_image',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_masters/packaging/', verbose_name='Packaging Image'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='vendor_details',
            field=models.TextField(blank=True, null=True, verbose_name='Vendor Details'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='vendor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Vendor Price'),
        ),
        migrations.CreateModel(
            name='BuyerMasterFinishingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='buyer_masters/finishing/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_images', to='erp.buyermaster')),
            ],
        ),
    ]
