# Generated by Django 5.2.16 on 2026-07-23 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
