# Generated by Django 5.2.16 on 2026-07-23 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_buyer_created_at_buyermaster_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_no', models.CharField(max_length=100, verbose_name='Style No.')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item / Product Name')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock Quantity')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Price (INR/USD)')),
                ('location', models.CharField(blank=True, default='Main Store', max_length=150, null=True, verbose_name='Storage Location')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Reserved', 'Reserved'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=30, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='erp.buyer', verbose_name='Buyer')),
                ('buyer_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='erp.buyermaster', verbose_name='Buyer Master')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='erp.supplierpoitem', verbose_name='Supplier PO Item')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='erp.sample', verbose_name='Sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
