# Generated by Django 5.2.16 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermaster',
            name='finish_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Finish Color'),
        ),
        migrations.AlterField(
            model_name='buyermaster',
            name='wood_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material / Wood Type'),
        ),
        migrations.AlterField(
            model_name='buyerpiitem',
            name='finish_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Finish'),
        ),
        migrations.AlterField(
            model_name='buyerpiitem',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='finish_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material'),
        ),
    ]
