# Generated by Django 5.2.16 on 2026-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_buyermaster_finish_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermaster',
            name='box_breadth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Breadth (cm)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='box_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Height (cm)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='box_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Box Length (cm)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price (USD)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='total_cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Total CBM'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='units',
            field=models.IntegerField(default=1, verbose_name='Units'),
        ),
    ]
