# Generated by Django 5.2.16 on 2026-07-23 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_buyermaster_box_breadth_buyermaster_box_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandingqc',
            name='assignment',
        ),
        migrations.AlterUniqueTogether(
            name='sandingbatch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sandingbatch',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='sandingbatch',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='sandingqc',
            name='checked_by',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_type',
            field=models.CharField(choices=[('raw', 'Raw Stock'), ('sanded', 'Sanded Stock'), ('polished', 'Polished Stock'), ('packaged', 'Packaged Stock (Finished)')], default='raw', max_length=20, verbose_name='Stock Type'),
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('sanding', 'Sanding'), ('polishing', 'Polishing'), ('packaging', 'Packaging')], max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('qc_requested', 'QC Requested'), ('qc_completed', 'QC Completed')], default='assigned', max_length=20)),
                ('style_no', models.CharField(max_length=100, verbose_name='Style No.')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item / Product Name')),
                ('assigned_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Assigned Quantity')),
                ('passed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Passed Quantity')),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rejected (Rework) Quantity')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('contractor_notes', models.TextField(blank=True, null=True, verbose_name='Contractor Notes')),
                ('qc_notes', models.TextField(blank=True, null=True, verbose_name='QC Feedback Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qc_requested_at', models.DateTimeField(blank=True, null=True)),
                ('qc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='erp.buyer')),
                ('buyer_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='erp.buyermaster')),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='erp.sample')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='erp.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionQCLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_qc_inspections', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_logs', to='erp.productionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SandingAssignment',
        ),
        migrations.DeleteModel(
            name='SandingBatch',
        ),
        migrations.DeleteModel(
            name='SandingQC',
        ),
    ]
