# Generated by Django 5.2.16 on 2026-07-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_remove_sandingqc_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
