# Generated by Django 5.2.16 on 2026-07-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_supplierpo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='samples/', verbose_name='Sample Image'),
        ),
    ]
