# Generated by Django 5.2.16 on 2026-07-25 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_sample_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Finish Name')),
                ('finish_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Finish Code')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('finish_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finish Type')),
                ('texture', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='finishes/', verbose_name='Finish Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finish',
                'verbose_name_plural': 'Finishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='erp.finish', verbose_name='Finish / Color Catalog'),
        ),
    ]
