# Generated by Django 5.2.16 on 2026-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_finish_sample_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='finish_type',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='texture',
        ),
        migrations.AddField(
            model_name='finish',
            name='wood_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wood Type'),
        ),
    ]
