# Generated by Django 5.2.16 on 2026-07-29 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_remove_finish_description_remove_finish_finish_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partial Received', 'Partial Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='GateInwardReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='Receipt Date')),
                ('challan_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Challan / Invoice No.')),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Received Qty')),
                ('passed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Passed Qty')),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rejected Qty')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_receipts', to='erp.supplierpoitem')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_receipts', to='erp.supplierpo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vch_type', models.CharField(default='Debit Note', max_length=50, verbose_name='Vch Type')),
                ('vch_no', models.CharField(max_length=100, unique=True, verbose_name='Debit Note No.')),
                ('vch_date', models.DateField(default=django.utils.timezone.now, verbose_name='Vch Date / Dated')),
                ('original_inv_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Invoice No.')),
                ('original_inv_date', models.DateField(blank=True, null=True, verbose_name='Original Invoice Date')),
                ('hsn_sac', models.CharField(default='70099200', max_length=50, verbose_name='HSN/SAC Code')),
                ('item_description', models.TextField(verbose_name='Description of Goods and Services')),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rejected Quantity')),
                ('unit', models.CharField(default='No.', max_length=30, verbose_name='Unit (No./pcs)')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rate (INR)')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal Amount')),
                ('cartage_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Pur Cartage GST Rate %')),
                ('cartage_gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Input CGST Rate %')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5, verbose_name='Input SGST Rate %')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Round Off')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Debit Note Amount (Max Rs 2 Lakh)')),
                ('amount_in_words', models.CharField(blank=True, max_length=300, null=True, verbose_name='Amount in Words')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('company_pan', models.CharField(default='ABXPS4077R', max_length=50, verbose_name="Company's PAN")),
                ('tally_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='erp.supplierpoitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='erp.supplier')),
                ('supplier_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='erp.supplierpo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
