# Generated by Django 5.2.16 on 2026-07-30 07:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_supplierpo_status_gateinwardreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Unit / Factory Name')),
                ('unit_code', models.CharField(max_length=50, unique=True, verbose_name='Unit Code')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location / Address')),
                ('capacity_pcs', models.IntegerField(default=1000, verbose_name='Monthly Capacity (pcs)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Unit',
                'verbose_name_plural': 'Production Units',
                'ordering': ['unit_code'],
            },
        ),
        migrations.AddField(
            model_name='productionjob',
            name='production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='erp.productionunit', verbose_name='Production Unit / Factory'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='erp.productionunit', verbose_name='Production Unit / Factory'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_pos', to='erp.productionunit', verbose_name='Production Unit / Factory'),
        ),
        migrations.AddField(
            model_name='user',
            name='production_unit',
            field=models.ForeignKey(blank=True, help_text='Assigned Factory / Production Unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='erp.productionunit'),
        ),
        migrations.CreateModel(
            name='UnitWorkReallocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reallocations', to='erp.buyer')),
                ('from_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocated_from', to='erp.productionunit')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_reallocations', to='erp.supplierpo')),
                ('reallocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reallocations', to=settings.AUTH_USER_MODEL)),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocated_to', to='erp.productionunit')),
            ],
            options={
                'verbose_name': 'Unit Work Re-allocation Audit',
                'verbose_name_plural': 'Unit Work Re-allocation Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerUnitAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_allocations', to='erp.buyer')),
                ('production_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_allocations', to='erp.productionunit')),
            ],
            options={
                'verbose_name': 'Buyer Unit Allocation',
                'verbose_name_plural': 'Buyer Unit Allocations',
                'unique_together': {('buyer', 'production_unit')},
            },
        ),
    ]
