# Generated by Django 5.2.16 on 2026-07-31 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_productionunit_productionjob_production_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='original_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Original PO Due Date'),
        ),
        migrations.CreateModel(
            name='POExtensionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_added', models.IntegerField(default=5, verbose_name='Days Added')),
                ('previous_due_date', models.DateField(blank=True, null=True, verbose_name='Previous Due Date')),
                ('new_due_date', models.DateField(verbose_name='New Due Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Call Notes / Extension Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Extended By')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_logs', to='erp.supplierpo', verbose_name='Supplier PO')),
            ],
            options={
                'verbose_name': 'PO Extension Log',
                'verbose_name_plural': 'PO Extension Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
