# Generated by Django 5.2.16 on 2026-07-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_supervisor_empty_strings(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE erp_supplierpo SET supervisor = NULL WHERE supervisor = '' OR supervisor IS NOT NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_supplierpo_original_due_date_poextensionlog'),
    ]

    operations = [
        migrations.RunPython(clean_supervisor_empty_strings, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productionjob',
            name='contractor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'contractor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierpo',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supplier_pos', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Supervisor'),
        ),
    ]
