# Generated by Django 5.2.16 on 2026-08-01 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_productionjob_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cartage_gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Cartage GST Rate (%)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cartage_ledger_name',
            field=models.CharField(default='PUR. CARTAGE GST @ 18% -  3 %', max_length=200, verbose_name='Cartage Ledger Name'),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='holding_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Grace Period End Time (2 Days)'),
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='status',
            field=models.CharField(choices=[('Grace Period', 'Grace Period (Pending Supplier Repair)'), ('Issued', 'Issued'), ('Resolved (Repaired)', 'Resolved (Repaired & Accepted)')], default='Issued', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supplierdebitnote',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Rejected Quantity'),
        ),
        migrations.AlterField(
            model_name='supplierdebitnote',
            name='unit',
            field=models.CharField(default='pcs', max_length=30, verbose_name='Unit (pcs/ft/kg)'),
        ),
        migrations.CreateModel(
            name='POSupplierHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Transfer')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erp.supplier')),
                ('previous_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='erp.supplier')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_history', to='erp.supplierpo')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierTaxInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100, verbose_name='Invoice No.')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Note')),
                ('despatch_document_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Despatch Document No.')),
                ('despatched_through', models.CharField(blank=True, max_length=100, null=True, verbose_name='Despatched Through')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination')),
                ('cartage_ledger_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cartage Ledger Name')),
                ('cartage_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Cartage GST Rate (%)')),
                ('cartage_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cartage Amount')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='erp.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supplierdebitnote',
            name='tax_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='erp.suppliertaxinvoice'),
        ),
        migrations.CreateModel(
            name='SupplierTaxInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hsn_sac', models.CharField(default='9403', max_length=50, verbose_name='HSN/SAC Code')),
                ('description', models.CharField(max_length=300, verbose_name='Description of Goods')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rate per Unit')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Disc %')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('passed_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='erp.supplierpoitem')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='erp.supplierpo')),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.suppliertaxinvoice')),
            ],
        ),
    ]
