# Generated by Django 5.2.16 on 2026-08-01 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_supplier_cartage_gst_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDebitNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('hsn_sac', models.CharField(default='9403', max_length=50)),
                ('rejected_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.supplierdebitnote')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.supplierpoitem')),
            ],
        ),
    ]
