# Generated by Django 5.2.16 on 2026-08-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_supplierdebitnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='buyer_pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_pos', to='erp.buyerpi', verbose_name='Linked Buyer PI Reference'),
        ),
        migrations.AddField(
            model_name='supplierpoitem',
            name='buyer_pi_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_allocations', to='erp.buyerpiitem', verbose_name='Buyer PI Item Reference'),
        ),
    ]
