# Generated by Django 5.2.16 on 2026-08-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_supplierpo_buyer_pi_supplierpoitem_buyer_pi_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Contact'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='grn_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GRN Number'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='round_number',
            field=models.IntegerField(default=1, verbose_name='Delivery Round Number'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='supplier_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Supplier Invoice Amount'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='supplier_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Supplier Invoice Date'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='supplier_invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Invoice No.'),
        ),
        migrations.AddField(
            model_name='gateinwardreceipt',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle / Truck No.'),
        ),
    ]
