# Generated by Django 5.2.16 on 2026-08-04 06:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_gateinwardreceipt_driver_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Master Base Rate (₹)')),
                ('current_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Effective Rate (₹)')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight per unit')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_items/', verbose_name='Item Image')),
                ('default_status', models.CharField(choices=[('charge', 'Chargeable'), ('non-charge', 'Non-Chargeable')], default='charge', max_length=20, verbose_name='Default Chargeability Status')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Reorder / Min Level')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark / Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Item',
                'verbose_name_plural': 'Store Items',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='StoreItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Category Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Store Item Category',
                'verbose_name_plural': 'Store Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=150, verbose_name='Worker / Delegate Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractor Person / Worker',
                'verbose_name_plural': 'Contractor Persons / Workers',
                'ordering': ['person_name'],
            },
        ),
        migrations.CreateModel(
            name='StoreDailyIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(max_length=100, verbose_name='Voucher No.')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('month_year', models.CharField(blank=True, help_text='e.g. Jul-26', max_length=30, null=True)),
                ('contractor_person_name', models.CharField(blank=True, help_text="Contractor's worker name e.g. Pappu - worker Raju", max_length=150, null=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Issued Qty')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Issue Rate (₹)')),
                ('status', models.CharField(choices=[('charge', 'Chargeable'), ('non-charge', 'Non-Chargeable')], default='charge', max_length=20, verbose_name='Charge Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Value (₹)')),
                ('chargeable_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Chargeable Total (₹)')),
                ('non_chargeable_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Non-Chargeable Total (₹)')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor', models.ForeignKey(help_text='Target Contractor / Supervisor', on_delete=django.db.models.deletion.CASCADE, related_name='store_issues', to=settings.AUTH_USER_MODEL)),
                ('contractor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='erp.contractorperson')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_store_items', to=settings.AUTH_USER_MODEL)),
                ('production_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_issues', to='erp.productionunit', verbose_name='Unit # / Factory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_issues', to='erp.storeitem')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storeitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='erp.storeitemcategory'),
        ),
        migrations.CreateModel(
            name='StoreItemRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('po_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_reason', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='erp.storeitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=100, unique=True, verbose_name='Store PO Number')),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued to Supplier'), ('received', 'Material Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_pos', to='erp.supplier')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreMaterialIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(max_length=100, unique=True, verbose_name='Inward Voucher No.')),
                ('inward_date', models.DateField(default=django.utils.timezone.now)),
                ('month_year', models.CharField(blank=True, help_text='e.g. Jul-26', max_length=30, null=True)),
                ('bill_no', models.CharField(max_length=100, verbose_name='Supplier Bill / Invoice #')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Received Qty')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('bill_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bill Rate (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount (₹)')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_entries', to='erp.storeitem')),
                ('production_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inwards', to='erp.productionunit')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inwards', to='erp.supplier')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_receipts', to='erp.storepurchaseorder')),
            ],
            options={
                'ordering': ['-inward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='erp.storeitem')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.storepurchaseorder')),
            ],
        ),
    ]
