# Generated by Django 5.2.16 on 2026-08-17 06:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_storeitem_storeitemcategory_contractorperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='system', max_length=150, verbose_name='User Name')),
                ('user_role', models.CharField(default='system', max_length=50, verbose_name='User Role')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent / Device')),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('UPDATE', 'Updated Record'), ('DELETE', 'Deleted Record'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('EXPORT', 'Exported Excel/PDF'), ('IMPORT', 'Imported Excel'), ('DOWNLOAD', 'Downloaded File')], default='UPDATE', max_length=30)),
                ('module_name', models.CharField(db_index=True, max_length=100, verbose_name='ERP Module')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Record ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Record Name / Summary')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Field Diffs')),
                ('file_info', models.JSONField(blank=True, default=dict, verbose_name='File Attachment Info')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Audit Note / Reason')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Audit Log',
                'verbose_name_plural': 'Global Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='erp_auditlo_user_id_edaa60_idx'), models.Index(fields=['module_name', '-timestamp'], name='erp_auditlo_module__556236_idx'), models.Index(fields=['action', '-timestamp'], name='erp_auditlo_action_637d47_idx')],
            },
        ),
    ]
