# Generated by Django 5.2.16 on 2026-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('contractor', 'Contractor'), ('store_manager', 'Store Manager'), ('merchant', 'Merchant')], default='contractor', max_length=20),
        ),
    ]
