# Generated by Django 5.2.16 on 2026-08-21 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMaterialReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(max_length=100, unique=True, verbose_name='Return Voucher No.')),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('month_year', models.CharField(blank=True, help_text='e.g. Jul-26', max_length=30, null=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Returned Qty')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Return Rate (₹)')),
                ('status', models.CharField(choices=[('charge', 'Chargeable'), ('non-charge', 'Non-Chargeable')], default='charge', max_length=20, verbose_name='Charge Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Value (₹)')),
                ('chargeable_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Chargeable Total (₹)')),
                ('non_chargeable_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Non-Chargeable Total (₹)')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor', models.ForeignKey(help_text='Contractor / Supervisor returning material', on_delete=django.db.models.deletion.CASCADE, related_name='store_returns', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_entries', to='erp.storeitem')),
                ('production_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_returns', to='erp.productionunit', verbose_name='Unit # / Factory')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_store_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-created_at'],
            },
        ),
    ]
