# Generated by Django 5.2.16 on 2026-08-22 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_storematerialreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_no', models.CharField(max_length=100, unique=True, verbose_name='Requisition No.')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Requested Qty')),
                ('unit', models.CharField(default='pcs', max_length=30, verbose_name='Unit')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose / Production Batch Note')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('issued', 'Stock Issued'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_requisitions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='erp.storeitem')),
                ('production_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_requisitions', to='erp.productionunit', verbose_name='Factory Unit')),
                ('requested_by', models.ForeignKey(help_text='Supervisor or Contractor requesting material', on_delete=django.db.models.deletion.CASCADE, related_name='store_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Material Requisition',
                'verbose_name_plural': 'Store Material Requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreStockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_no', models.CharField(max_length=100, unique=True, verbose_name='Adjustment No.')),
                ('adjustment_type', models.CharField(choices=[('evaporation', 'Liquid Evaporation'), ('damage', 'Material Damage'), ('wastage', 'Production Wastage'), ('physical_audit', 'Physical Audit Adjustment')], default='physical_audit', max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity Delta (Negative for Loss, Positive for Gain)')),
                ('reason', models.TextField(verbose_name='Audit Note / Reason')),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved & Stock Synced'), ('rejected', 'Rejected')], default='pending_admin', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='erp.storeitem')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Stock Adjustment',
                'verbose_name_plural': 'Store Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
