# Generated by Django 5.2.16 on 2026-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_storerequisition_storestockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('security', 'Security & Logins'), ('inventory', 'Store & Inventory'), ('orders', 'Purchase & Orders'), ('production', 'Production & QC'), ('system', 'System Alerts')], default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
