# Generated by Django 5.2.16 on 2026-10-01 09:00

from django.db import migrations, models


def backfill_finish_category(apps, schema_editor):
    Finish = apps.get_model('erp', 'Finish')
    Finish.objects.filter(models.Q(category__isnull=True) | models.Q(category='')).update(category='wood')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_notification_category_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedailyissue',
            options={'ordering': ['-created_at', '-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store Item', 'verbose_name_plural': 'Store Items'},
        ),
        migrations.AlterModelOptions(
            name='storematerialin',
            options={'ordering': ['-created_at', '-inward_date']},
        ),
        migrations.AlterModelOptions(
            name='storematerialreturn',
            options={'ordering': ['-created_at', '-return_date']},
        ),
        migrations.AddField(
            model_name='finish',
            name='category',
            field=models.CharField(choices=[('wood', 'Wood Finish'), ('metal', 'Metal Finish'), ('marble', 'Marble Finish'), ('fabric', 'Fabric Type')], default='wood', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='finish',
            name='coating_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coating / Process'),
        ),
        migrations.AddField(
            model_name='finish',
            name='marble_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marble Type'),
        ),
        migrations.AddField(
            model_name='finish',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabric Material'),
        ),
        migrations.AddField(
            model_name='finish',
            name='metal_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Metal Type'),
        ),
        migrations.AddField(
            model_name='finish',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pattern / Texture'),
        ),
        migrations.AddField(
            model_name='finish',
            name='surface_treatment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surface Treatment'),
        ),
        migrations.RunPython(backfill_finish_category, migrations.RunPython.noop),
    ]
