# Generated by Django 5.2.16 on 2026-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_storedailyissue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finish',
            name='plastic_finish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surface / Transparency'),
        ),
        migrations.AddField(
            model_name='finish',
            name='plastic_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plastic / Polymer Type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabric Type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='marble_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marble Finish'),
        ),
        migrations.AddField(
            model_name='sample',
            name='metal_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metal Finish'),
        ),
        migrations.AddField(
            model_name='sample',
            name='plastic_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plastic Type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='wood_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wood Finish'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='category',
            field=models.CharField(choices=[('wood', 'Wood Finish'), ('metal', 'Metal Finish'), ('marble', 'Marble Finish'), ('fabric', 'Fabric Type'), ('plastic', 'Plastic Type')], default='wood', max_length=20, verbose_name='Category'),
        ),
    ]
