# Generated by Django 5.2.16 on 2026-10-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_finish_plastic_finish_finish_plastic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermaster',
            name='ctn',
            field=models.IntegerField(blank=True, null=True, verbose_name='CTN (Units per Box)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabric Type'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='fob_city',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='FOB CITY (Price per Unit)'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='leg_color',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Leg Color'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='marble_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marble Finish'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='metal_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metal Finish'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='plastic_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plastic Type'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='table_top_color',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Table Top Colour'),
        ),
        migrations.AddField(
            model_name='buyermaster',
            name='wood_finish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wood Finish'),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
