# Generated by Django 5.2.16 on 2026-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_buyermaster_ctn_buyermaster_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermaster',
            name='ctn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CTN (Units per Box)'),
        ),
    ]
